name: Push

on:
  push:
    branches: [ "develop", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Upload Android Release to Play Store
          uses: r0adkll/upload-google-play@v1
